--ORDER BY SÜTÜNDAKİ VERİLERİ SIRALAMAMIZI SAĞLAR. ASC ARTAN DESC İSE AZALAN OLARAK SIRALAR.
--LIMIT KOMUTU KAÇ VERİ İSTEDİĞİMİZİ BELİRTMEMİZİ SAĞLAR.
SELECT * FROM film WHERE title LIKE('%n') ORDER BY length desc LIMIT 5;

SELECT * FROM film WHERE title LIKE('%n') ORDER BY length OFFSET 5 LIMIT 5;

SELECT * FROM customer WHERE customer_id=1 ORDER BY last_name desc LIMIT 4